language: php

php:
- 7.2
- 7.3
- 7.4

install:
- travis_retry composer install --no-interaction --no-suggest

script:
- vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
- travis_retry php vendor/bin/coveralls
  # or enable logging
- travis_retry php vendor/bin/coveralls -v

branches:
  only:
  - develop